[package]
name = "csv2json"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
anyhow = "1.0.43"
clap = "3.0.0-beta.4"
csv = "1.1.6"
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
serde_json = "1.0.67"
unescape = "0.1.0"
